[build][build]

base = "client"base = "client"

command = "npm ci && npm run build"command = "npm ci && npm run build"

publish = ".next"publish = ".next"



[[plugins]][[plugins]]

package = "@netlify/plugin-nextjs"package = "@netlify/plugin-nextjs"



[context.production.environment][context.production.environment]

NODE_ENV = "production"NODE_ENV = "production"


[context.production]
environment = { NODE_ENV = "production" }
